[Behavior]
AutoSelectionDelay=600
BookmarkOpenMethod=new_window
ConfirmDelete=true
ConfirmTrash=false
CtrlRightClick=false
NoUsbTrash=false
QuickExec=false
RecentFilesNumber=0
SelectNewFiles=false
SingleClick=false
SingleWindowMode=false
UseTrash=true

[Desktop]
AllSticky=false
BgColor=#000000
DesktopCellMargins=@Size(3 1)
DesktopIconSize=48
DesktopShortcuts=@Invalid()
FgColor=#ffffff
Font="Adwaita Sans,11,-1,5,400,0,0,0,0,0,0,0,0,0,0,1,,0,0"
HideItems=false
LastSlide=
NoItemTooltip=false
OpenWithDefaultFileManager=false
PerScreenWallpaper=false
ScreenNames=@Invalid()
ShadowColor=#000000
ShowHidden=false
SlideShowInterval=0
SortColumn=mtime
SortFolderFirst=true
SortHiddenLast=false
SortOrder=descending
TransformWallpaper=false
Wallpaper=
WallpaperDialogSize=@Size(700 500)
WallpaperDialogSplitterPos=200
WallpaperDirectory=
WallpaperMode=none
WallpaperRandomize=false
WorkAreaMargins=12, 12, 12, 12

[FolderView]
BackupAsHidden=false
BigIconSize=72
CustomColumnWidths=@Invalid()
FolderViewCellMargins=@Size(7 7)
HiddenColumns=3, 4, 6, 7
Mode=icon
NoItemTooltip=true
ScrollPerPixel=false
ShadowHidden=true
ShowFilter=false
ShowFullNames=true
ShowHidden=true
SidePaneIconSize=24
SmallIconSize=32
SortCaseSensitive=false
SortColumn=type
SortFolderFirst=false
SortHiddenLast=true
SortOrder=ascending
ThumbnailIconSize=128

[Places]
HiddenPlaces=/home/mark/Desktop, network:///, menu://applications/, computer:///

[Search]
ContentPatterns=@Invalid()
MaxSearchHistory=0
NamePatterns=@Invalid()
searchContentCaseInsensitive=false
searchContentRegexp=true
searchNameCaseInsensitive=false
searchNameRegexp=true
searchRecursive=false
searchhHidden=false

[System]
Archiver=xarchiver
FallbackIconThemeName=oxygen
OnlyUserTemplates=false
SIUnit=false
SuCommand=lxqt-sudo %s
TemplateRunApp=false
TemplateTypeOnce=false
Terminal=kitty

[Thumbnail]
MaxExternalThumbnailFileSize=-1
MaxThumbnailFileSize=102400
ShowThumbnails=true
ThumbnailLocalFilesOnly=false

[Volume]
AutoRun=true
CloseOnUnmount=true
MountOnStartup=true
MountRemovable=true

[Window]
AlwaysShowTabs=false
Buttons=back
FixedHeight=480
FixedWidth=640
HideWindowBorders=true
LastWindowHeight=1060
LastWindowMaximized=false
LastWindowWidth=1326
PathBarButtons=false
PathMode=text
RememberWindowSize=true
ReopenLastTabs=false
ShowMenuBar=false
ShowStatusbar=false
ShowTabClose=false
ShowToolbar=true
SidePaneMode=places
SidePaneVisible=true
SplitView=false
SplitViewTabsNum=0
SplitterPos=156
SwitchToNewTab=false
TabPaths=@Invalid()
